server:
  port: ${CUSTOM.SERVER.PORT:9080}

# Cloud Gateway Routes
spring:
  cloud:
    gateway:
      routes:        

        - id: user-service-route
          uri: lb://user-service
          predicates:
            - Path=/api/user-service/**
          filters:
            - StripPrefix=2

        - id: driver-license-service-route
          uri: lb://driver-license-service  # 9020
          predicates:
            - Path=/api/driver-license-service/**
          filters:
            - StripPrefix=2

        - id: driver-license-query-service-route
          uri: lb://driver-license-query-service # 9022
          predicates:
            - Path=/api/driver-license-query-service/**
          filters:
            - StripPrefix=2
            
        - id: driver-license-command-service-route
          uri: lb://driver-license-command-service # 9920
          predicates:
            - Path=/api/driver-license-command-service/**
          filters:
            - StripPrefix=2


# Actuator configuration         
management:
  endpoints:
    web:
      exposure:
        include: '*'
        base-path: /actuator
# Zipkin configuration   
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN.SERVER.HOSTNAME:http://localhost:9411/api/v2/spans}

# Logging Configuration
# logging:
#   level:
#     reactor:
#       netty: ALL

mitocode:
  security:
    key: d5ae6cbc368bca70ba27f88bcfb569a41a26bc80cacf28b65757987e7679101a7bd97e46bc29fd44c2116ca83657d66646ccfa29fc86e7288fa703101b616b57b5cedab8a996bdbb496958da84d55fa7fb64488455f133f0b9df8e23202589f5